name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout out the repository
        uses: actions/checkout@v3.3.0
      - name: Setup Java JDK on ${{ matrix.os }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven on ${{ matrix.os }}
        run: mvn package
        env:
          MAVEN_OPTS: -Djava.awt.headless=true
      - name: Run unit tests
        run: mvn test
        env:
          MAVEN_OPTS: -Djava.awt.headless=true
      - name: Generate JaCoCo report
        run: mvn test jacoco:report
        env:
          MAVEN_OPTS: -Djava.awt.headless=true
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
        env:
          MAVEN_OPTS: -Djava.awt.headless=true
      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target/
      - name: Upload the test coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-artifact
          path: target/site/jacoco/
      - name: Upload the documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation-artifact
          path: target/apidocs/